model_params:
  latent_dim: 500
  conv_filters: [64, 128, 256, 512]
  kernel_size: 3

training_params:
  learning_rate: 0.001
  epochs: 50
  batch_size: 100

data_params:
  image_size : 64
  channels : 3

paths:
  ressources  : "ressources/"
  save_encoder: "training/encoder_cat_vae.keras"
  save_decoder: "training/decoder_cat_vae.keras"