model_params:
  latent_dim: 10
  conv_filters: [64, 128, 256, 512,1]
  kernel_size: 3

training_params:
  learning_rate: 0.0002
  epochs: 5
  batch_size: 100

data_params:
  image_size : 64

paths:
  save_generator: "training/generator.keras"
  save_discriminator: "training/discriminator_cat_vae.keras"